version: '2.15'
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_container
    ports:
      - "3000:3000"
    volumes:
      - ./myblog:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api